# Generated by Django 5.2.8 on 2025-12-01 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_article_created_at_alter_article_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="core_visit_date_e33ba1_idx"),
                    models.Index(
                        fields=["session_key"], name="core_visit_session_e759da_idx"
                    ),
                ],
                "unique_together": {("session_key", "date"), ("user", "date")},
            },
        ),
    ]
